# -*- coding: utf-8 -*-
"""1.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Usig7zChSkOr7CN2pfg4fD-nYku2qZ76
"""

image_path = '/content/Assignment-main/Data Visualization/images'
json_path = '/content/Assignment-main/Data Visualization/data'
alpha = 0.5

import os
from IPython.display import Image
import json
# from google.colab.patches import cv2_imshow
import numpy as np
import cv2
import random
from .. import utils
from utils import get_denormalized_cordinates,mark

for i in range(len(os.listdir(image_path))):
  subpath1 = str(i+1) + ".jpg"
  subpath2 = str(i+1) + ".json"
  img_path = os.path.join(image_path,subpath1)
  data_path = os.path.join(json_path,subpath2)
  output = mark(img_path,data_path,alpha)
  cv2.imshow(output)

