# -*- coding: utf-8 -*-
"""CarScan Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TNB_lSGx0oBbndk5or0xSyzBoZn7xRcT
"""

image_path = '/content/Assignment-main/Damage Identification/images'
json_path = '/content/Assignment-main/Damage Identification/data'

import os
import json
import numpy as np
from shapely.geometry import Polygon
from .. import utils2
from utils2 import solve,get_denormalized_cordinates

for i in range(len(os.listdir(image_path))):
  subpath1 = str(i+1) + ".jpg"
  subpath2 = str(i+1) + "-car-parts.json"
  subpath3 = str(i+1) + "-damages.json"
  img_path = os.path.join(image_path,subpath1)
  data_path = os.path.join(json_path,subpath2)
  damage_path = os.path.join(json_path,subpath3)
  output = solve(img_path,data_path,damage_path)
  for i in output:
    print(i)
  print()





