# -*- coding: utf-8 -*-
"""utils2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pbIE6gbBrDrWN92wVOltxhwxYiuihoKB
"""

import os
import json
import numpy as np
from shapely.geometry import Polygon

def get_denormalized_cordinates(data_path):
  denormalized_points = []
  data = open(data_path)
  info = json.load(data)
  for i in info:
    if(i['type']=="polygonlabels"):
      points = i['value']['points']
      width = i['original_width']
      height = i['original_height']
      for j in range(np.shape(points)[0]):
        points[j][0] = points[j][0]*width/100
        points[j][1] = points[j][1]*height/100
      carpart = i['value']['polygonlabels']
      temp = {}
      points = np.asarray(points,np.int32)
      temp['id'] = i['id']
      temp['part'] = carpart
      temp['points'] = points
      denormalized_points.append(temp)
  data.close()
  return denormalized_points

def solve(img_path,data_path,damage_path):
  a = []
  carparts = get_denormalized_cordinates(data_path)
  damages = get_denormalized_cordinates(damage_path)
  for i in carparts:
    for j in damages:
      p1 = Polygon(i['points'])
      p2 = Polygon(j['points'])
      if (p1.intersects(p2)==True):
        dictionary = {}
        dictionary['part-id'] = i['id']
        dictionary['part'] = i['part']
        dictionary['damages'] = j['part']
        dictionary['carpoly'] = i['points']
        dictionary['damagepoly'] = j['points']
        a.append(dictionary)
  ans = {}
  for i in a:
    if i['part-id'] in ans:
      p2 = i['damagepoly']
      p2 = Polygon(p2)
      temp['damage'] = temp['damage'] + p1.intersection(p2).area
      temp['count'] = temp['count'] + 1
    else:
      temp = {}
      temp['name'] = i['part']
      temp['damages'] = j['part']
      p1 = i['carpoly']
      p2 = i['damagepoly']
      p1 = Polygon(p1)
      p2 = Polygon(p2) 
      temp['count'] = 1
      temp['area'] = p1.area
      temp['damage'] = p1.intersection(p2).area
      ans[i['part-id']] = temp
  # print(ans)
  string = []
  for i in ans:
    temp = "Found " + str(ans[i]['count']) + " " + ans[i]['damages'][0] + " on part " + ans[i]['name'][0] + " with percentage " + str(ans[i]['damage']*100/ans[i]['area'])
    string.append(temp)
  return string

